### ISSUE TITLE
Cross-Account Replication

### ISSUE THREAD

**Issue by jordanmendler** [awslabs/dynamodb-import-export-tool#3]
Have you guys ever done cross-account replication with the tool? If not, any tips on the simplest way to implement it. Looking to get it done in the next week if anyone has some pointers. Happy to submit back a patch if we can get it working.

**Comment by amcp** [comment]
You would need to use STS to vend yourself temporary credentials for the third party account with an IAM role, provided that you have already coordinated with the third party account for access. Then you would need to pass in both credentials to the tool. Currently, the command line interface does not support this mode of operation, but because the API allows you to create the client yourself, you could write a program that uses IAM and STS to get temporary credentials for use in one of the DynamoDB clients.

**Comment by ShruNaik** [comment]
I was trying to replicate using the following method:
-> Use Streams to get an update from the primary database 
->Trigger an SNS notification in the Primary Acct that writes to the SQS Queue in the Replica Account
-> A Lambda Reads from this SQS Queue and the write to the Replica DynamoDB

Is the STS method more reliable in case there are multiple replicas?
